name: Pylint Check

on:
  push:
    branches:
      - dev

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pylint
        id: pylint
        run: |
          pylint $(find . -name "*.py") > pylint-report.txt || true

      # - name: Upload Pylint report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: pylint-report
      #     path: pylint-report.txt

      - name: Pylint with dynamic badge
        uses: Silleellie/pylint-github-action@v2
        with:
          lint-path: src
          python-version: 3.10
